services:
  postulamatic_web:
    build: .
    # env_file: .env
    restart: unless-stopped
    networks: [web]
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - redis
    environment:
      - OPENAI_API_KEY=your-openai-api-key-here
      - ANTHROPIC_API_KEY=your-anthropic-api-key-here
      - SECRET_KEY=your-secret-key-here
      - DEBUG=True
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - GUNICORN_CMD_ARGS=--timeout 180
  worker:
    build: .
    # env_file: .env
    command: bash -c "cd /app && celery -A postulamatic worker -l info"
    restart: unless-stopped
    environment:
      - DISPLAY=:99
    networks: [web]
    volumes:
      - .:/app
    depends_on:
      - redis
  beat:
    build: .
    # env_file: .env
    command: celery -A postulamatic beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    restart: unless-stopped
    networks: [web]
    volumes:
      - .:/app
    depends_on:
      - redis
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks: [web]
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    restart: unless-stopped
    networks: [web]
    ports:
      - "8191:8191"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - HEADLESS=true
      - TEST_URL=https://www.google.com

networks:
  web:
    external: true

