# Generated by Django 5.2.6 on 2024-09-27 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(blank=True, max_length=100, null=True)),
                ('smtp_host', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_port', models.IntegerField(default=587)),
                ('smtp_use_tls', models.BooleanField(default=True)),
                ('smtp_use_ssl', models.BooleanField(default=False)),
                ('smtp_username', models.CharField(blank=True, max_length=255, null=True)),
                ('smtp_password', models.TextField(blank=True, null=True)),
                ('dv_username', models.CharField(blank=True, max_length=255, null=True)),
                ('dv_password', models.TextField(blank=True, null=True)),
                ('match_threshold', models.IntegerField(default=70, help_text='Umbral de coincidencia 0-100')),
                ('daily_limit', models.IntegerField(default=20, help_text='Límite diario de envíos')),
                ('min_pause_seconds', models.IntegerField(default=20, help_text='Pausa mínima entre envíos')),
                ('max_pause_seconds', models.IntegerField(default=90, help_text='Pausa máxima entre envíos')),
                ('is_active', models.BooleanField(default=False, help_text='Start/Stop del proceso automático')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
            },
        ),
    ]
