# Generated by Django 5.2.6 on 2025-10-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_encrypt_existing_credentials'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='dv_connection_status',
            field=models.CharField(choices=[('verified', 'Verificado'), ('not_verified', 'No Verificado')], default='not_verified', help_text='Estado de conexión a INTRANET DAVINCI', max_length=20),
        ),
    ]
