# Generated by Django 5.2.6 on 2025-10-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0005_emailsentlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openai_api_key', models.CharField(blank=True, help_text='API Key de OpenAI (sk-...)', max_length=255)),
                ('openai_model', models.CharField(default='gpt-3.5-turbo', help_text='Modelo de OpenAI a usar', max_length=100)),
                ('openai_enabled', models.BooleanField(default=False, help_text='Habilitar OpenAI')),
                ('anthropic_api_key', models.CharField(blank=True, help_text='API Key de Anthropic (sk-ant-...)', max_length=255)),
                ('anthropic_model', models.CharField(default='claude-3-haiku-20240307', help_text='Modelo de Anthropic a usar', max_length=100)),
                ('anthropic_enabled', models.BooleanField(default=False, help_text='Habilitar Anthropic')),
                ('default_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], default='openai', help_text='Proveedor por defecto', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración de IA',
                'verbose_name_plural': 'Configuración de IA',
            },
        ),
    ]
