# Generated by Django 5.2.6 on 2025-11-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("matching", "0010_emailsentlog_personalized_cv_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="auto_send_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Activar envío automático diario de emails a nuevos matches",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="auto_send_last_run",
            field=models.DateTimeField(
                blank=True,
                help_text="Última vez que se ejecutó el envío automático",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="auto_send_time",
            field=models.TimeField(
                default="09:00:00",
                help_text="Hora del día para envío automático (formato 24h)",
            ),
        ),
    ]
